---
# name: certificates
# file: tasks/certs.yml

- name: "Copy certificates to {{ item.dest }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
