---
# role: ansible-role-certificates
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: meta/requirements.yml
driver:
  name: podman
lint: |
  set -e
  ansible-lint
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    prepare: "../resources/playbooks/prepare.yml"
    verify: "../resources/playbooks/verify.yml"
  inventory:
    group_vars:
      all:
        certificates_run_once: true
        certificates_host: "certificates_ca_host"
        certificates_ca_certs:
          - src: "/etc/ssl/ca/example/pub/root-ca.pem"
            dest: "{{ certificates_ca_trust_dir }}/example-root-ca.crt"
          - src: "/etc/ssl/ca/example/pub/intermediate-ca.pem"
            dest: "{{ certificates_ca_trust_dir }}/example-intermediate-ca.crt"
          - src: "/etc/ssl/ca/example/pub/component-ca.pem"
            dest: "{{ certificates_ca_trust_dir }}/example-component-ca.crt"
          - src: "/etc/ssl/ca/example/pub/identity-ca.pem"
            dest: "{{ certificates_ca_trust_dir }}/example-identity-ca.crt"
    host_vars:
      certificates:
        certificates_certs:
          - src: "/etc/ssl/ca/example/dist/fritzbox.pem"
            dest: "{{ certificates_tls_dir }}/certs/fritzbox.pem"
            mode: "0644"
          - src: "/etc/ssl/ca/example/dist/fritzbox-fullchain.pem"
            dest: "{{ certificates_tls_dir }}/certs/fritzbox-fullchain.pem"
            mode: "0644"
          - src: "/etc/ssl/ca/example/dist/fritzbox.key"
            dest: "{{ certificates_tls_dir }}/private/fritzbox.key"
            mode: "0600"
verifier:
  name: ansible
platforms:
  - name: certificates_ca_host
    image: "docker.io/jam82/molecule-alpine:latest"
    pre_build_image: true
    networks:
      - name: certificates
  - name: certificates
    image: "docker.io/${uns:-jam82}/molecule-${img:-fedora}:${tag:-latest}"
    pre_build_image: true
    networks:
      - name: certificates
