---
# role: ansible-role-certificates
# file: molecule/resources/playbooks/converge.yml

- name: "PLAYBOOK | Converge"
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
